@extends('layouts.cavernas')

@section('content')
<section class="page-heading page-heading-theme compact-heading"><p class="eyebrow">Administrator panel</p><h1>Lifecycle<br><em>overview.</em></h1><p>Review frozen, inactive, and archived characters and jump directly into staff editing.</p></section>
<section class="admin-management-card admin-filter-panel"><form method="GET" class="admin-filter-form"><label>Search character or player<input type="search" name="search" value="{{ $search }}" placeholder="Name"></label><button class="button button-primary" type="submit">Filter</button>@if ($search)<a class="text-link" href="{{ route('admin.lifecycle.index') }}">Clear</a>@endif</form></section>
<section class="admin-management-grid">
    <article class="admin-management-card"><div class="section-heading"><div><p class="eyebrow">Frozen characters</p><h2>Held in place.</h2></div></div>@forelse ($frozen as $character)<div class="admin-lifecycle-row"><div><a href="{{ route('staff.characters.edit', $character) }}"><strong>{{ $character->name }}</strong></a><span>{{ $character->user->name }} · {{ $character->frozen_reason ?: 'No reason recorded' }}</span></div><small>{{ $character->energy }}/100 energy</small></div>@empty<p class="form-intro">No frozen characters.</p>@endforelse{{ $frozen->links() }}</article>
    <article class="admin-management-card"><div class="section-heading"><div><p class="eyebrow">Inactive characters</p><h2>Needs attention.</h2></div></div>@forelse ($inactive as $character)<div class="admin-lifecycle-row"><div><a href="{{ route('staff.characters.edit', $character) }}"><strong>{{ $character->name }}</strong></a><span>{{ $character->user->name }} · {{ $character->inactive_at?->format('M j, Y') ?: 'Date unknown' }}</span></div><small>{{ $character->energy }}/100 energy</small></div>@empty<p class="form-intro">No inactive characters.</p>@endforelse{{ $inactive->links() }}</article>
</section>
<section class="admin-management-card admin-lifecycle-archive"><div class="section-heading"><div><p class="eyebrow">Archived characters</p><h2>Lives remembered.</h2></div></div>@forelse ($archived as $character)<div class="admin-lifecycle-row"><div><a href="{{ route('staff.characters.edit', $character) }}"><strong>{{ $character->name }}</strong></a><span>{{ $character->user->name }} · {{ $character->died_at?->format('M j, Y') ?: 'Death date unknown' }}</span></div><small>{{ $character->allegiance }} · {{ $character->role }}</small></div>@empty<p class="form-intro">No archived characters.</p>@endforelse{{ $archived->links() }}</section>
@endsection
