@extends('layouts.staff')

@section('content')
<section class="page-heading page-heading-theme compact-heading"><p class="eyebrow">Staff desk</p><h1>Character<br><em>records.</em></h1><p>Review ownership, allegiance, role, and lifecycle status before opening a full staff edit.</p></section>
<section class="admin-management-card staff-character-records">
	<div class="section-heading"><div><p class="eyebrow">Directory</p><h2>All character records.</h2></div><span>{{ $characters->total() }} {{ $characters->total() === 1 ? 'character' : 'characters' }}</span></div>
	<div class="character-directory-scroll"><table class="character-directory-table staff-character-table"><thead><tr><th>Character</th><th>Player</th><th>Allegiance</th><th>Role</th><th>Status</th><th></th></tr></thead><tbody>@forelse ($characters as $character)<tr><td><a class="directory-identity" href="{{ route('characters.show', $character) }}">@php($portrait = $character->images[0] ?? $character->forum_avatar_path ?? $character->avatar_path)@if ($portrait)<img src="{{ filter_var($portrait, FILTER_VALIDATE_URL) ? $portrait : asset('storage/'.$portrait) }}" alt="{{ $character->name }} portrait">@else<span class="directory-avatar">{{ strtoupper(substr($character->name, 0, 1)) }}</span>@endif<span class="directory-name"><strong>{{ $character->name }}</strong></span></a></td><td>{{ $character->user->name }}</td><td><span class="directory-allegiance"><span class="clan-dot {{ strtolower($character->allegiance) }}" aria-hidden="true"></span>{{ $character->allegiance }}</span></td><td>{{ ucfirst(str_replace('_', ' ', $character->role)) }}</td><td><span class="staff-record-status is-{{ $character->status }}">{{ ucfirst($character->status) }}</span></td><td><a class="button" href="{{ route('staff.characters.edit', $character) }}">Edit</a></td></tr>@empty<tr><td colspan="6"><div class="forum-empty"><h2>No character records.</h2><p>Character records will appear here after creation.</p></div></td></tr>@endforelse</tbody></table></div>
	{{ $characters->links() }}
</section>
@endsection
