@extends('layouts.staff')

@section('content')
<section class="form-panel"><p class="eyebrow">Staff character tools</p><h1>Edit<br><em>{{ $character->name }}.</em></h1>@if (session('status'))<div class="form-success">{{ session('status') }}</div>@endif @if ($errors->any())<div class="form-alert">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('staff.characters.update', $character) }}" enctype="multipart/form-data" class="cavernas-form">@csrf @method('PATCH')
<div class="form-columns"><label>Name<input name="name" value="{{ old('name', $character->name) }}" required></label><label>Sex<select name="sex"><option value="female" @selected(old('sex', $character->sex) === 'female')>She-cat</option><option value="male" @selected(old('sex', $character->sex) === 'male')>Tom</option></select></label></div>
<div class="form-columns"><label>Age in moons<input name="age_moons" type="number" min="0" max="240" step="0.5" value="{{ old('age_moons', $character->age_moons) }}"></label><label>Eye color<input name="eye_color" value="{{ old('eye_color', $character->eye_color) }}"></label></div>
<div class="form-columns"><label>Allegiance<select name="allegiance">@foreach (['ThunderClan','RiverClan','ShadowClan','WindClan','outsider','Kittypet','Loner','Rogue'] as $allegiance)<option value="{{ $allegiance }}" @selected(old('allegiance', $character->allegiance) === $allegiance)>{{ $allegiance }}</option>@endforeach</select></label><label>Role<select name="role">@foreach (['kit','apprentice','warrior','queen','elder','leader','deputy','medicine_cat','medicine_cat_apprentice','kittypet','loner','rogue'] as $role)<option value="{{ $role }}" @selected(old('role', $character->role) === $role)>{{ $role }}</option>@endforeach</select></label></div>
<div class="form-columns"><label>Status<select name="status">@foreach (['active','inactive','deceased'] as $status)<option value="{{ $status }}" @selected(old('status', $character->status) === $status)>{{ $status }}</option>@endforeach</select></label><label>Energy<input type="number" name="energy" min="0" max="100" value="{{ old('energy', $character->energy) }}"></label></div>
<label>Looks<input name="looks" value="{{ old('looks', $character->looks) }}"></label>
<label>Appearance<textarea name="appearance" rows="5">{{ old('appearance', $character->appearance) }}</textarea></label>
<label>Personality<textarea name="personality" rows="5">{{ old('personality', $character->personality) }}</textarea></label>
<label>History<textarea name="history" rows="5">{{ old('history', $character->history) }}</textarea></label>
<label>Disability<input name="disability" value="{{ old('disability', $character->disability) }}"></label>
<label>Portraits <small>Three image URLs or files in total.</small><input type="file" name="images[]" accept="image/jpeg,image/png,image/webp" multiple></label>
<label>Image URLs or saved images<textarea name="image_urls" rows="3">{{ old('image_urls', implode("\n", $character->images ?? [])) }}</textarea></label>
<label>Forum avatar<input type="file" name="forum_avatar" accept="image/jpeg,image/png,image/webp"></label>
<label class="checkbox-label"><input type="checkbox" name="role_locked" value="1" @checked($character->role_locked)> Lock role from automatic age changes</label><label class="checkbox-label"><input type="checkbox" name="is_frozen" value="1" @checked($character->is_frozen)> Freeze character lifecycle</label><label>Freeze reason<input name="frozen_reason" value="{{ old('frozen_reason', $character->frozen_reason) }}" placeholder="adoption, sale, staff hold"></label><button class="button button-primary" type="submit">Save character <span aria-hidden="true">→</span></button></form></section>
@if ($character->role === 'medicine_cat_apprentice')<section class="form-panel character-mentor-panel"><p class="eyebrow">Medicine cat training</p><h2>Assign a mentor</h2><form method="POST" action="{{ route('staff.characters.medicine-mentor', $character) }}" class="cavernas-form">@csrf<label>Medicine cat<select name="mentor_id" required><option value="">Choose medicine cat</option>@foreach ($medicineCats as $mentor)<option value="{{ $mentor->id }}" @selected($character->mentors()->whereKey($mentor->id)->exists())>{{ $mentor->name }}</option>@endforeach</select></label><button class="button button-primary" type="submit">Assign mentor</button></form></section>@endif
@endsection
