@extends('layouts.cavernas')

@section('content')
<section class="page-heading page-heading-theme compact-heading"><p class="eyebrow">Administrator panel</p><h1>Forum and<br><em>sidebar structure.</em></h1><p>Create, edit, and order the spaces members use to find the world.</p></section>
@if (session('status'))<div class="form-success">{{ session('status') }}</div>@endif
@if ($errors->any())<div class="form-alert" role="alert">{{ $errors->first() }}</div>@endif
<section class="admin-management-grid">
    <article class="admin-management-card"><div class="section-heading"><div><p class="eyebrow">Forum categories</p><h2>Organize the world.</h2></div></div>
        @foreach ($categories as $category)<form method="POST" action="{{ route('admin.content.categories.update', $category) }}" class="admin-inline-form">@csrf @method('PATCH')<input name="name" value="{{ $category->name }}" required><input name="description" value="{{ $category->description }}"><input type="number" name="sort_order" value="{{ $category->sort_order }}" min="0"><button class="text-link" type="submit">Save</button></form>@endforeach
        <form method="POST" action="{{ route('admin.content.categories.store') }}" class="admin-create-form">@csrf<h3>New category</h3><input name="name" placeholder="Category name" required><input name="description" placeholder="Description"><input type="number" name="sort_order" value="0" min="0"><button class="button button-primary" type="submit">Create</button></form>
    </article>
    <article class="admin-management-card"><div class="section-heading"><div><p class="eyebrow">Forum boards</p><h2>Shape each path.</h2></div></div>
        @foreach ($categories as $category)@foreach ($category->boards as $board)<form method="POST" action="{{ route('admin.content.boards.update', $board) }}" class="admin-inline-form admin-board-form">@csrf @method('PATCH')<select name="forum_category_id">@foreach ($categories as $option)<option value="{{ $option->id }}" @selected($option->id === $category->id)>{{ $option->name }}</option>@endforeach</select><input name="name" value="{{ $board->name }}" required><input name="description" value="{{ $board->description }}"><input type="number" name="sort_order" value="{{ $board->sort_order }}" min="0"><label class="checkbox-label"><input type="checkbox" name="is_ic" value="1" @checked($board->is_ic)> IC</label><button class="text-link" type="submit">Save</button></form>@endforeach @endforeach
        <form method="POST" action="{{ route('admin.content.boards.store') }}" class="admin-create-form">@csrf<h3>New board</h3><select name="forum_category_id" required>@foreach ($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select><input name="name" placeholder="Board name" required><input name="description" placeholder="Description"><input type="number" name="sort_order" value="0" min="0"><label class="checkbox-label"><input type="checkbox" name="is_ic" value="1"> In character</label><button class="button button-primary" type="submit">Create</button></form>
    </article>
</section>
<section class="admin-management-card admin-modules-card"><div class="section-heading"><div><p class="eyebrow">Sidebar modules</p><h2>Cards in the shell.</h2></div></div>
    @foreach ($modules as $module)<form method="POST" action="{{ route('admin.content.modules.update', $module) }}" class="admin-inline-form admin-module-form">@csrf @method('PATCH')<input name="title" value="{{ $module->title }}" required><input name="body" value="{{ $module->body }}" required><input name="link_text" value="{{ $module->link_text }}"><input name="link_url" value="{{ $module->link_url }}"><select name="placement"><option value="left" @selected($module->placement === 'left')>Left</option><option value="right" @selected($module->placement === 'right')>Right</option></select><input type="number" name="sort_order" value="{{ $module->sort_order }}" min="0"><label class="checkbox-label"><input type="checkbox" name="is_enabled" value="1" @checked($module->is_enabled)> Live</label><button class="text-link" type="submit">Save</button></form>@endforeach
    <form method="POST" action="{{ route('admin.content.modules.store') }}" class="admin-create-form">@csrf<h3>New sidebar module</h3><input name="title" placeholder="Title" required><textarea name="body" placeholder="Module copy" rows="3" required></textarea><input name="link_text" placeholder="Link text"><input name="link_url" placeholder="Link URL"><select name="placement"><option value="left">Left sidebar</option><option value="right">Right sidebar</option></select><input type="number" name="sort_order" value="0" min="0"><label class="checkbox-label"><input type="checkbox" name="is_enabled" value="1" checked> Live</label><button class="button button-primary" type="submit">Create</button></form>
</section>
@endsection
