@extends('layouts.staff')

@section('content')
<section class="page-heading page-heading-theme compact-heading"><p class="eyebrow">Administrator panel</p><h1>Sidebar<br><em>modules.</em></h1><p>Cards shown in the left or right sidebar shell.</p></section>
@if (session('status'))<div class="form-success">{{ session('status') }}</div>@endif
@if ($errors->any())<div class="form-alert" role="alert">{{ $errors->first() }}</div>@endif
<section class="admin-management-card admin-modules-card">
    <div class="section-heading"><div><p class="eyebrow">Existing modules</p><h2>Cards in the shell.</h2></div></div>
    @if ($modules->isNotEmpty())<form method="POST" action="{{ route('admin.content.modules.bulk-update') }}" class="admin-bulk-form">@csrf @method('PATCH')@foreach ($modules as $module)<div class="admin-inline-form admin-module-form"><input name="modules[{{ $module->id }}][title]" value="{{ $module->title }}" required><input name="modules[{{ $module->id }}][body]" value="{{ $module->body }}" required><input name="modules[{{ $module->id }}][link_text]" value="{{ $module->link_text }}"><input name="modules[{{ $module->id }}][link_url]" value="{{ $module->link_url }}"><select name="modules[{{ $module->id }}][placement]"><option value="left" @selected($module->placement === 'left')>Left</option><option value="right" @selected($module->placement === 'right')>Right</option></select><input type="number" name="modules[{{ $module->id }}][sort_order]" value="{{ $module->sort_order }}" min="0"><label class="checkbox-label"><input type="hidden" name="modules[{{ $module->id }}][is_enabled]" value="0"><input type="checkbox" name="modules[{{ $module->id }}][is_enabled]" value="1" @checked($module->is_enabled)> Live</label></div>@endforeach<div class="admin-page-save"><button class="button button-primary" type="submit">Save changes</button></div></form>@endif
    <form method="POST" action="{{ route('admin.content.modules.store') }}" class="admin-create-form">@csrf<h3>New sidebar module</h3><input name="title" placeholder="Title" required><textarea name="body" placeholder="Module copy" rows="3" required></textarea><input name="link_text" placeholder="Link text"><input name="link_url" placeholder="Link URL"><select name="placement"><option value="left">Left sidebar</option><option value="right">Right sidebar</option></select><input type="number" name="sort_order" value="0" min="0"><label class="checkbox-label"><input type="checkbox" name="is_enabled" value="1" checked> Live</label><button class="button button-primary" type="submit">Create</button></form>
</section>
@endsection
